# Day 1

In [1]:
# ipynb full form is  ' interective python notebook '

In [2]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [4]:
arr_1d = np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [5]:
type(arr_1d)

numpy.ndarray

In [6]:
arr_1d.ndim  # it give anser that means inwhich diamention array have.

1

In [7]:
arr_2d =np.array([[1,2,3,4],[5,6,7,8]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr_2d.ndim

2

In [9]:
print(arr_1d)

print(arr_1d.size)   # it give array no. of element which store in array

print(len(arr_1d))  # it give array lenght

[1 2 3 4 5]
5
5


In [10]:
print(arr_2d)

print()
print(arr_2d.size)    # it give array no. of element which store in array
print()

print(len(arr_2d))    # it give array lenght

[[1 2 3 4]
 [5 6 7 8]]

8

2


# shape

In [11]:
arr_2d.shape

(2, 4)

In [12]:
arr_1d.shape

(5,)

In [13]:
arr_2d.dtype

dtype('int32')

# Day 2

In [14]:
np.array([[1,1,1],[1,1,1],[1,1,1]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
mx_1s = np.ones(5)  # value by defult is float
mx_1s

array([1., 1., 1., 1., 1.])

In [16]:
mx_1s.dtype

dtype('float64')

In [17]:
mx_1s = np.ones((3,4))
mx_1s

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
mx_1s = np.ones((3,4),dtype=int)  # create array as a integer value
mx_1s

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
mx_0s = np.zeros((4,6))
mx_0s

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
mx_0s = np.zeros((4,6), dtype=bool)
mx_0s

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [21]:
mx_0s = np.zeros((4,6), dtype=str)
mx_0s

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [22]:
em_str = ''
bool(em_str)

False

In [23]:
em_mx = np.empty((3,3))
em_mx

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.77460587e-321],
       [1.78019082e-306, 1.37959740e-306, 2.29178686e-312]])

# Day 3

# Numpy Function :

# arange()

In [24]:
import numpy as np

In [25]:
# np.arange(star, Ende, steps)
ar_1d  = np.arange(1,13)
ar_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
even_ar = np.arange(1, 13, 2)  # it always make array less than 1 of end number
even_ar

array([ 1,  3,  5,  7,  9, 11])

# linspace()

In [27]:
np.linspace(1,5,4)  # it give array of size 4 and  4 value assign in array  between 1 and 5

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [28]:
ar_1d = np.arange(1,13)
ar_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
ar_2d =  ar_1d.reshape(2,6)
ar_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
ar_2d =  ar_1d.reshape(3,4)
ar_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
ar_23d =  ar_1d.reshape(2,3,2)
ar_23d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [32]:
print(ar_23d[0][0])

print()

print(ar_23d[0][1])

print()

print(ar_23d[0][2])



[1 2]

[3 4]

[5 6]


In [33]:
ar = np.arange(1,13).reshape(2,6)
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# revel()

In [34]:
ar.ravel()     # it convert multy diamention array to 1d diamention and it not change original array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [35]:
ar.flatten()     # it also convert multy diamention array to 1d diamention and it not change original array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# transpose()  and T

In [37]:
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [38]:
ar.transpose() 

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [39]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [40]:
ar2 = np.arange(1,19).reshape(3,6)
ar2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [41]:
ar2.transpose()

array([[ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18]])

In [42]:
ar2.T

array([[ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18]])

In [43]:
ar3 = np.arange(1,13)
ar3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
ar3.transpose()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Mathematic Operation Using Numpy

In [45]:
import numpy as np

In [46]:
arr1 = np.arange(1,10).reshape(3,3)
arr2= np.arange(1,10).reshape(3,3)

print(arr1)
print()
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
print(arr1 + arr2)

print()

print(np.add(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [48]:
print(arr1 - arr2)

print()

print(np.subtract(arr1, arr2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [49]:
np.multiply(arr1, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [50]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
arr1 @ arr2     # cross product and than addition of 1st row of arr1  to 1st colum of arr2 

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [52]:
arr1.dot(arr2)   # this another way to cross product and than addition of 1st row of arr1  to 1st colum of arr2 

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [53]:
print(arr1)
print()
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
print(arr1.max())

print()

print(arr2.max())

print()
print()

print(arr1.min())

print()

print(arr2.min())

9

9


1

1


In [55]:
print(arr1)

print()

print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
arr1.argmax()  # it give index of maximum value in matrix

8

In [57]:
arr1.argmin()  # it give index of minimum value in matrix

0

In [58]:
arr1.max(axis=0)  # it give maximum value of every colum in matrix

# NOTE : 1 represent row and 0 represent colum 

array([7, 8, 9])

In [59]:
arr3 = arr1.max(axis=0)  # it give maximum value of every colum in matrix

print(arr3)

print()

for i in arr3:
    print(i)

[7 8 9]

7
8
9


In [60]:
arr1.max(axis=1)  # it give maximum value of every row in matrix

array([3, 6, 9])

In [61]:
print(arr1)

print()

print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
print(np.sum(arr1))  # it give sum number of entire matrix

print()

print(np.sum(arr1, axis=0))  # it give sum number of every colum of matrix and give collection of array 

print()

print(np.sum(arr1, axis=1))  # it give sum number of every row of matrix and give collection of array


45

[12 15 18]

[ 6 15 24]


In [63]:
print(arr1)

print()

print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
print(np.mean(arr1))

print()

print(np.sqrt(arr1))

print()

print(np.std(arr1))  # find standered deviation

print()

print(np.exp(arr1))  # find expontial

print()

print(np.log(arr1))  #find simple log 

print()

print(np.log10(arr1))  # find log base 10

5.0

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

2.581988897471611

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]


# Day 4

# Python Numpy Array slicing (:)

In [65]:
import numpy as np

In [66]:
mx = np.arange(1,101).reshape(10,10)
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [67]:
mx.ndim   # this is 2D array Thus the output is 2

2

In [68]:
mx[0,0]

1

In [69]:
mx[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
mx[:,0]  # all row with only 1st colum print and store  as a new array

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [71]:
mx[:,0].ndim  # 1D array than output is 1

1

In [72]:
mx[:,:5]   

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55],
       [61, 62, 63, 64, 65],
       [71, 72, 73, 74, 75],
       [81, 82, 83, 84, 85],
       [91, 92, 93, 94, 95]])

In [73]:
mx[:,0:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55],
       [61, 62, 63, 64, 65],
       [71, 72, 73, 74, 75],
       [81, 82, 83, 84, 85],
       [91, 92, 93, 94, 95]])

In [74]:
mx[:,0:5].ndim   # 2D array than output is 2

2

In [75]:
mx[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [76]:
mx.itemsize

4

In [77]:
mx.dtype

dtype('int32')

In [78]:
32/8  # 32 bit dtype and 8 bit of itemsize than   32/8 = 4 bytes

4.0

# Day 5

# Python Numpy Array Concatination and Split

In [79]:
import numpy as np

In [80]:
arr1 = np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [81]:
arr2 = np.arange(17,33).reshape(4,4)
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [82]:
list1 = [2,4,6,8]
list2 = [1,8,3,5]

In [83]:
list1 + list2

[2, 4, 6, 8, 1, 8, 3, 5]

In [84]:
arr1 + arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [85]:
np.concatenate((arr1,arr2))   # concatenate by default colum wise concatenate

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [86]:
np.concatenate((arr1,arr2), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [87]:
np.concatenate((arr1,arr2), axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [88]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [89]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [90]:
np.hstack((arr1,arr2,arr1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [95]:
print(arr1)
print()
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [91]:
list1 =  np.split(arr1,2)  # arr1 will be convert into 2 part of array and both array store in the list
list1

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [92]:
for i in list1:
    print(i)
    
print()
print(type(list1))

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]

<class 'list'>


In [93]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
type(list1[0])

numpy.ndarray

In [97]:
print(arr1)
print()
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [96]:
np.split(arr1, 2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [102]:
d1 = np.array([4,5,1,2,9,23,12,34,12,34,12,43,34,24])
d1

array([ 4,  5,  1,  2,  9, 23, 12, 34, 12, 34, 12, 43, 34, 24])

In [104]:
np.split(d1,[3,7])  

[array([4, 5, 1]),
 array([ 2,  9, 23, 12]),
 array([34, 12, 34, 12, 43, 34, 24])]

# part 8, 9, 10 ye part  baki hai vidio  watch karne ke liye